### ISSUE TITLE
Bump Ubuntu Server 22.04 LTS AMI IDs to the latest

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#119]
Update VMwareLinuxBastionInstance EC2 AMI affected by the recent OpenSSL security vulnerability CVE-2022-3786 & CVE-2022-3602

More info:
https://www.openssl.org/news/secadv/20221101.txt
https://ubuntu.com/security/CVE-2022-3786
https://ubuntu.com/security/CVE-2022-3602

This work is the enhancement of  [PR-115](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/pull/115/)

**Comment by satya-dillikar** [comment]
I have tested the below AWS SSM CLI and Cloud-formation template

@tlindsay42 ,  Is it okay to replace hard-corded AMI values for US2204HVM with
/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id

**SSM CLI:**
```
aws ssm get-parameters --names /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id --region us-east-2
{
    "Parameters": [
        {
            "Name": "/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id",
            "Type": "String",
            "Value": "ami-03ba6c40a876f6ed6",
            "Version": 15,
            "LastModifiedDate": "2022-11-01T11:25:46.059000-07:00",
            "ARN": "arn:aws:ssm:us-east-2::parameter/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id",
            "DataType": "aws:ec2:image"
        }
    ],
    "InvalidParameters": []
}


```

**CFT template for the same**


```

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation template
Parameters:
  LatestAmiId:
    Description: >-
      LatestAmiId
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  LatestAmiId:
    Description: >-
      LatestAmiId
    Value: !Ref LatestAmiId

```
