### ISSUE TITLE
 Reduce the number of load balancers (w.r.t cost)

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#31]
**Summary**:  Currently TAP uses two load balancers. Replace with one LB or NLB etc. Evaluate.

```
metadata_store:
  ns_for_export_app_cert: #@ data.values.repositories.workload.namespace
  app_service_type: LoadBalancer

contour:
  envoy:
    service:
      type: LoadBalancer

```
**Suggested Assignee**: Troy
**Priority**: P3
